export const darkTheme = {
    mode: 'dark',
    PRIMARY_BACKGROUND_COLOR: '#222',
    PRIMARY_TEXT_COLOR: '#CCC',
    PRIMARY_BUTTON_COLOR: '#',
    PRIMARY_BUTTON_TEXT_COLOR: '#',
    PRIMARY_BORDER_COLOR: '#777',
    UPLOAD_BACKGROUND_COLOR: '#bbb',
    UPLOAD_TEXT_COLOR: '#bbb5',
    UPLOAD_BORDER_COLOR: '#bbb'
}
export const lightTheme = {
    mode: 'light',
    PRIMARY_BACKGROUND_COLOR: '#CCC',
    PRIMARY_TEXT_COLOR: '#222',
    PRIMARY_BUTTON_COLOR: '#',
    PRIMARY_BUTTON_TEXT_COLOR: '#',
    PRIMARY_BORDER_COLOR: '#999',
    UPLOAD_BACKGROUND_COLOR: '#bbb5',
    UPLOAD_TEXT_COLOR: '#bbb',
    UPLOAD_BORDER_COLOR: '#bbb5'
}